// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAPI.Dataaccess;

#nullable disable

namespace TaskAPI.Dataaccess.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20230206100214_AuthorEntityAndData")]
    partial class AuthorEntityAndData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "saman"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "pahan"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "laman"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "nisan"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Created = new DateTime(2023, 2, 6, 15, 32, 14, 552, DateTimeKind.Local).AddTicks(124),
                            Description = "just todo 1 from database",
                            Due = new DateTime(2023, 2, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 0,
                            Title = "todo1"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            Created = new DateTime(2023, 2, 6, 15, 32, 14, 552, DateTimeKind.Local).AddTicks(145),
                            Description = "just todo 2 from database",
                            Due = new DateTime(2023, 2, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 0,
                            Title = "todo1"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Created = new DateTime(2023, 2, 6, 15, 32, 14, 552, DateTimeKind.Local).AddTicks(147),
                            Description = "just todo 3 from database",
                            Due = new DateTime(2023, 2, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 0,
                            Title = "todo1"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            Created = new DateTime(2023, 2, 6, 15, 32, 14, 552, DateTimeKind.Local).AddTicks(149),
                            Description = "just todo 4 from database",
                            Due = new DateTime(2023, 2, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 0,
                            Title = "todo1"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.HasOne("TaskAPI.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
